project:
  type: website

website:
  title: "T-matrix"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/nano-optics/tmatrix
          - text: Discussion
            url:  https://github.com/nano-optics/tmatrix/discussions
    left:
      - text: "Exporting to HDF5"
        menu:
        - export_julia.qmd 
        - export_matlab.qmd 
        - export_python.qmd 
        - export_R.qmd
      - text: "Conversion long/wide"
        file: conversion.qmd
      - text: "Indexing reference"
        file: indexing.qmd
      - text: "Displaying T-matrices"
        file: display.qmd
      - text: "SMARTIES"
        menu:
        - smarties.qmd
        - smarties_batch.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



